ViewModels/FurnitureListViewModel.cs
using FurnitureStore.Data.Models;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.ViewModels
{
    public class FurnitureListViewModel
    {
        public IEnumerable<Furniture> allFurniture { get; set; }
    }
}

Controllers/FurnitureController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FurnitureStore.Data.Interfaces;
using FurnitureStore.ViewModels;
using FurnitureStore.Data.Models;
using Microsoft.AspNetCore.Http;
using System.Drawing;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using FurnitureStore.Data;
using Microsoft.AspNetCore.Authorization;

namespace FurnitureStore.Controllers
{
    public class FurnitureController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationContext _applicationContext;
        private readonly IRepository<Furniture> _allFurnituries;
        private readonly IRepository<Comments> _allComments;
        private readonly IRepository<FurnitureKind> _furnitureKind;
        private readonly IRepository<FurnitureType> _furnitureType;
        private readonly IRepository<FurnitureColor> _furnitureColor;
        private readonly IRepository<Stock> _stock;
        private readonly ShopCart _shopCart;

        public FurnitureController(ApplicationContext applicationContext,IWebHostEnvironment IWebHostEnvironment, ShopCart shopCart, IRepository<Furniture> iallFurnituries, IRepository<FurnitureKind> ifurnitureKind,
            IRepository<FurnitureType> ifurnitureType, IRepository<FurnitureColor> ifurnitureColor, IRepository<Stock> iStock, IRepository<Comments> allComments)
        {
            _applicationContext = applicationContext;
            _environment = IWebHostEnvironment;
            _allComments = allComments;
            _allFurnituries = iallFurnituries;
            _furnitureKind = ifurnitureKind;
            _furnitureType = ifurnitureType;
            _furnitureColor = ifurnitureColor;
            _stock = iStock;
            _shopCart = shopCart;
        }
        public async Task<FurnitureListViewModel> Sort(int furnitureID,string name,string?[] stockFilter,string?[] kindFilter, string?[] typeFilter, string?[] colorFilter, int price1, int price2)
        {
            FurnitureListViewModel fur = new FurnitureListViewModel();
            List<Furniture> filter = new List<Furniture>();
            List<Furniture> filter1 = new List<Furniture>();
            var enumerable = await _allFurnituries.ListAsync();

            if (furnitureID != 0)
            {
                fur.allFurniture = enumerable.Where(i => i.FurnitureID == furnitureID);
                return fur;
            }
            else
            {
                if (kindFilter.Any())
                {
                    foreach (var item in enumerable)
                    {
                        foreach (var el in kindFilter.ToList())
                        {
                            if (item.FurnitureKind.Kind == el) filter.Add(item);
                        }
                    }
                }
                else
                {
                    filter = enumerable.ToList();
                }
                if (typeFilter.Any())
                {
                    foreach (var item in filter)
                    {
                        foreach (var el in typeFilter)
                        {
                            if (item.FurnitureType.Type == el) filter1.Add(item);
                        }
                    }
                }
                else
                {
                    filter1 = filter;
                }
                filter = new List<Furniture>();
                if (colorFilter.Any())
                {
                    foreach (var item in filter1)
                    {
                        foreach (var el in colorFilter)
                        {
                            if (item.FurnitureColor.ColorName == el) filter.Add(item);
                        }
                    }
                }
                else
                {
                    filter = filter1;
                }

                filter1 = new List<Furniture>();
                if (price2 != 0)
                {
                    foreach (var item in filter)
                    {
                        if ((item.Price >= price1) && (item.Price <= price2)) filter1.Add(item);
                    }
                }
                else
                {
                    filter1 = filter;
                }
                filter = new List<Furniture>();
                if (stockFilter.Any())
                {
                    foreach (var item in filter1)
                    {
                        foreach (var el in stockFilter)
                        {
                            if (item.Stock.StockName == el) filter.Add(item);
                        }
                    }
                }
                else
                {
                    filter = filter1;
                }
                if(name!="" && name!=null)
                {
                    filter = filter.Where(i => i.Name.ToLower().Contains(name.ToLower())).ToList();
                }

                fur.allFurniture = filter.Where(i => i.Number > 0);
                return fur;
            }
        }
        public async Task<IActionResult> List()
        {
            ViewData["Path"] = _environment.WebRootPath;
            ViewBag.Items = _shopCart.GetShopItems().Select(i => i.furniture.FurnitureID);
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            ViewBag.Types = await _furnitureType.ListAsync();
            ViewBag.Colors = await _furnitureColor.ListAsync();
            ViewBag.Stock = await _stock.ListAsync();
            var furList=await _allFurnituries.ListAsync();
            FurnitureListViewModel fur = new FurnitureListViewModel
            {
                allFurniture = furList.Where(i => i.Number > 0)
            };
            return View(fur);
        }
        [HttpPost]
        public async Task<IActionResult> List(int furnitureID, string name, string[] stockFilter, string[] kindFilter, string[] typeFilter, string[] colorFilter, int price1, int price2)
        {
            ViewData["Path"] = _environment.WebRootPath;
            ViewBag.Items = _shopCart.GetShopItems().Select(i => i.furniture.FurnitureID);
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            ViewBag.Types = await _furnitureType.ListAsync();
            ViewBag.Colors = await _furnitureColor.ListAsync();
            ViewBag.Stock = await _stock.ListAsync();
            return View(Sort(furnitureID,name,stockFilter,kindFilter, typeFilter, colorFilter, price1, price2).Result);
        }
        public IActionResult Test (string kind)
        {
            Console.WriteLine(kind);
            string[] stockFilter = new string[] { };
            string[] kindFilter = new string[] {kind};
            string[] typeFilter = new string[] { };
            string[] colorFilter = new string[] { };
            int price1=0;
            int price2=0;
            return RedirectToAction("List", new  { stockFilter=stockFilter, kindFilter= kindFilter, typeFilter=typeFilter, colorFilter = colorFilter, price1=price1, price2=price2 });
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> FurnitureList()
        {
            ViewData["Path"] = _environment.WebRootPath;
            ViewBag.Items = _shopCart.GetShopItems().Select(i => i.furniture.FurnitureID);
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            ViewBag.Types = await _furnitureType.ListAsync();
            ViewBag.Colors = await _furnitureColor.ListAsync();
            ViewBag.Stock = await _stock.ListAsync();
            FurnitureListViewModel fur = new FurnitureListViewModel
            {
                allFurniture = await _allFurnituries.ListAsync()
            };
            return View(fur);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> FurnitureList(int furnitureID, string name, string?[] stockFilter, string?[] kindFilter, string?[] typeFilter, string?[] colorFilter, int price1, int price2)
        {
            ViewData["Path"] = _environment.WebRootPath;
            ViewBag.Items = _shopCart.GetShopItems().Select(i => i.furniture.FurnitureID);
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            ViewBag.Types = await _furnitureType.ListAsync();
            ViewBag.Colors = await _furnitureColor.ListAsync();
            ViewBag.Stock = await _stock.ListAsync();
            return View(Sort(furnitureID,name,stockFilter,kindFilter, typeFilter, colorFilter, price1, price2).Result);
            
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Create(string error)
        {
            ViewData["Error"] = error;
            ViewBag.Kinds = new SelectList(await _furnitureKind.ListAsync(), "KindID", "Kind");
            ViewBag.Types = new SelectList(await _furnitureType.ListAsync(), "TypeID", "Type");
            ViewBag.Colors = new SelectList(await _furnitureColor.ListAsync(),"ColorID","ColorName");
            ViewBag.Stock = new SelectList(await _stock.ListAsync(), "StockID", "StockName");
            return View();
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> Create(Furniture fur,IFormFile pic1, IFormFile pic2, IFormFile pic3)
        {
            List<Furniture> furnituries = (List<Furniture>)await _allFurnituries.ListAsync();
            if (furnituries.Exists(i => i.Name.ToLower() == fur.Name.ToLower()))
            {
                return base.RedirectToAction("Create", new { error = "Мебель с таким названием уже существует" });
            }
            await _allFurnituries.CreateAsync(fur);

Controllers/ShopCartController.cs
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.Data.Repository;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IRepository<Furniture> _furRep;
        private readonly ShopCart _shopCart;
        private readonly IWebHostEnvironment _environment;

        public ShopCartController(IWebHostEnvironment environment,IRepository<Furniture> furRep,ShopCart shopCart)
        {
            _environment = environment;
            _furRep = furRep;
            _shopCart = shopCart;
        }
        public ViewResult Index()
        {
            ViewData["Path"] = _environment.WebRootPath;
            _shopCart.ListShopItems = _shopCart.GetShopItems();
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _furRep.GetAsync(id).Result;
            if (item != null) 
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult Delete(int id)
        {
            _shopCart.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Furniture/FurnitureList.cshtml
@model FurnitureListViewModel


<form method="post">
    <style>
        .container {
            width: 99%;
            padding-right: 10px;
            padding-left: 10px;
            margin-right: auto;
            margin-left: auto;
        }
        
        .col-sm-1 {
            -ms-flex: 0 0 2%;
            flex: 0 0 2%;
            max-width: 2%;
        }
        .border {
            border-width:2px;
            border-color:white;
        }
        .number {
          width:12em;
        }
        th {
        color: white;
        }
    </style>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <a class="btn btn-info col-md-12" asp-controller="Furniture" asp-action="Create" asp-route-error="">Добавить</a><br/><br/><br/>

                <button class="btn btn-success col-md-12" type="submit">Фильтрация</button><br><br>

                <a class="btn btn-primary col-md-12" data-toggle="collapse"  data-target="#hide">Номер мебели</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide">
                    <div class="col-md-12">
                        <table class="table table-bordered">
                            <tbody>
                            @{
                                <tr>
                                    <td scope="row" style="background-color:white">
                                        <input class="col-md-12" style="color:black" type="number" min="0" name="furnitureID" id="furnitureID">
                                    </td>
                                </tr>  
                            }
                            <tbody>
                        </table>
                     </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse"  data-target="#hide1">Название</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide1">
                    <div class="table-responsive col-md-12">
                        <table class="table table-bordered">
                            <tbody class="form-check">
                                <tr>
                                    <td scope="row" style="background-color:white">
                                        <input style="color:black" class="form-check-input col-md-12" type="text" name="name" id="name">
                                    </td>
                                </tr>
                            <tbody>
                        </table>
                    </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse"  data-target="#hide2">Акции</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide2">
                    <div class="table-responsive col-md-12">
                        <table class="table table-info table-bordered">
                            <tbody class="form-check">
                                @{
                                    foreach (var el in  ViewBag.Stock)
                                    {
                                        <tr>
                                            <td scope="row">
                                                <input class="form-check-input" type="checkbox" name="stockFilter" value="@el.StockName" id="@el.StockName">
                                                <label class="form-check-label" for="@el.StockName">@el.StockName</label>
                                            </td>
                                        </tr>
                                    }
                                }
                            <tbody>
                        </table>
                    </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse"  data-target="#hide3">Вид мебели</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide3">
                    <div class="table-responsive col-md-12">
                        <table class="table table-info table-bordered">
                            <tbody class="form-check">
                                @{
                                    foreach (var el in  ViewBag.Kinds)
                                    {
                                        <tr>
                                            <td scope="row">
                                                <input class="form-check-input" type="checkbox" name="kindFilter" value="@el.Kind" id="@el.Kind">
                                                <label class="form-check-label" for="@el.Kind">@el.Kind</label>
                                            </td>
                                        </tr>
                                    }
                                }
                            <tbody>
                        </table>
                    </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse" data-target="#hide4">Тип мебели</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide4">
                    <div class="table-responsive col-md-12">
                        <table class="table table-bordered">
                            <tbody class="form-check">
                                @{
                                    foreach (var el in ViewBag.Types)
                                    {
                                        <tr>
                                            <td scope="row">
                                                <input class="form-check-input" type="checkbox" name="typeFilter" value="@el.Type" id="@el.Type">
                                                <label class="form-check-label" for="@el.Type">@el.Type</label>
                                            </td>
                                        </tr>
                                    }
                                }
                            <tbody>
                        </table>
                    </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse" data-target="#hide5">Основной цвет</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide5">
                    <div class="table-responsive col-md-12">
                        <table class="table table-bordered">
                            <tbody class="form-check">
                                @{
                                    foreach (var el in ViewBag.Colors)
                                    {
                                        <tr>
                                            <td scope="row">
                                                <input class="form-check-input col-md-2" type="checkbox" value="@el.ColorName" name="colorFilter"  id="@el.ColorName ">
                                                <label class="form-check-label col-md-7" for="@el.ColorName">@el.ColorName</label>
                                                <input name="color" type="color" style="text-align: center; font-weight: bolder;" value="@el.Color" class="col-md-3" disabled>
                                            </td>
                                        </tr>
                                    }
                                }
                                <tbody>
                        </table>
                    </div>
                </div>

                <a class="btn btn-primary col-md-12" data-toggle="collapse" data-target="#hide6">Цена</a>
                <br><br>
                <div class="panel-collapse collapse in row" id="hide6">
                    <div class="table-responsive col-md-12">
                        <table class="table table-bordered">
                            <tbody class="form-check">
                                <tr>
                                    <td scope="row">
                                        От <input type="number" class="number" min="0" value="0" name="price1"/> Руб.<br/><br/>
                                        До <input type="number" class="number" min="0" value="0" name="price2" /> Руб.
                                    </td>
                                </tr>
                                <tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-md-10">
                @{
                    foreach (var el in Model.allFurniture)
                    {
                         if (el.Number==0)
                         {
                             <div class="col-md-6 alert alert-danger border">
                                
                                <div class="col-md-7">
                                    
                                    <label>@el.Name</label>
                                    <br>
                                    <h5>Вид: @el.FurnitureKind.Kind</h5>
                                    <h5>Тип: @el.FurnitureType.Type</h5>
                                    <h5>Цвет: @el.FurnitureColor.ColorName</h5>
                                    <h5>Количество: @el.Number</h5>
                                </div>
                                <div class="col-md-5">
                                    <a class="btn btn-info col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="FurniturePage">Выбрать</a>
                                    <a class="btn btn-info col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="Edit" asp-route-error="">Изменить</a>
                                    <a class="btn btn-danger col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="Delete">Удалить</a>
                                </div>
                            </div>
                         }
                         else
                         {
                            <div class="col-md-6 alert alert-info border">
                                <div class="col-md-7">
                                    <label>@el.Name</label>
                                    <br>
                                    <h5>Вид: @el.FurnitureKind.Kind</h5>
                                    <h5>Тип: @el.FurnitureType.Type</h5>
                                    <h5>Цвет: @el.FurnitureColor.ColorName</h5>
                                    <h5>Количество: @el.Number</h5>
                                </div>
                                <div class="col-md-5">
                                    <a class="btn btn-info col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="FurniturePage">Выбрать</a>
                                    <a class="btn btn-info col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="Edit" asp-route-error="">Изменить</a>
                                    <a class="btn btn-danger col-md-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="Delete">Удалить</a>
                                </div>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </div>
</form>

Views/Furniture/FurniturePage.cshtml
@model FurnitureListViewModel

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />    
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

<style>
        .container {
            width: 90%;
            padding-right: 10px;
            padding-left: 10px;
            margin-right: auto;
            margin-left: auto;
        }
</style>
<div class="container" >
    <div class="col-md-10">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-height:20em">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" style="max-height:20em">
                    <div class="item active">
                        <img src="@Model.allFurniture.FirstOrDefault().Photo1" class="center-block"  style="max-height:20em">
                    </div>

                    <div class="item">
                        <img src="@Model.allFurniture.FirstOrDefault().Photo2" class="center-block"  style="max-height:20em">
                    </div>

                    <div class="item">
                        <img src="@Model.allFurniture.FirstOrDefault().Photo3" class="center-block"  style="max-height:20em">
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        <div class="center-img">
            @{
                foreach (var furniture in Model.allFurniture)
                {
                    <h4><strong >Основные характеристики:</strong></h4>
                    <table class="table-bordered">
                        <tr>
                            <td class="col-md-3">Вид</td>
                            <td class="col-md-3">@furniture.FurnitureKind.Kind</td>
                        </tr>

                        <tr>
                            <td class="col-md-3">Тип</td>
                            <td class="col-md-3">@furniture.FurnitureType.Type</td>
                        </tr>

                        <tr>
                            <td class="col-md-3">Основной цвет</td>
                            <td class="col-md-3">@furniture.FurnitureColor.ColorName</td>
                        </tr>
                        <tr>
                            <td class="col-md-3">Материал</td>
                            <td class="col-md-3">@furniture.Material</td>
                        </tr>
                   </table>
                   <br/>
                   <h4><strong>Габариты:</strong></h4>
                   <table class="table-bordered">
                        <tr>
                            <td class="col-md-3">Ширина</td>
                            <td class="col-md-3">@furniture.Width</td>
                        </tr>

                        <tr>
                            <td class="col-md-3">Высота</td>
                            <td class="col-md-3">@furniture.Height</td>
                        </tr>

                        <tr>
                            <td class="col-md-3">Длинна</td>
                            <td class="col-md-3">@furniture.Length</td>
                        </tr>
                   </table>
                   <br/>
                   <h4><strong>Описание:</strong></h4>
                   <p class="text-break">@furniture.LongDesc</p> 
                   <br/>
                   <a data-toggle="collapse" aria-expanded="true" data-target="#hide1">
                        <h4><strong>Комментарии<b class="caret"></b></strong></h4>
                   </a>
                   <div id="hide1" class="panel-collapse collapse in row">
                       <table class="col-md-12 table-bordered">
                            @foreach(var el in furniture.Comments.OrderByDescending(i=>i.Date))
                            {
                                <tr>
                                    <td align="center" class="col-md-2">
                                        <img src="@el.Avatar" class="col-md-12">
                                        @el.UserName <br/>
                                        @el.Date
                                    </td>
                                    <td class="col-md-3"><label>@el.Comment</label></td>
                                    <td class="col-md-2">
                                        <a data-fancybox="gallery" href="@el.Photo">
                                            <img class="col-md-12" src="@el.Photo">
                                        </a>
                                    </td>
                                    <td class="col-md-2">
                                        <a data-fancybox="gallery" href="@el.Photo2">
                                            <img class="col-md-12" src="@el.Photo2">
                                        </a>
                                    </td>
                                    <td class="col-md-2">
                                        <a data-fancybox="gallery" href="@el.Photo3">
                                            <img class="col-md-12" src="@el.Photo3">
                                        </a>
                                    </td>
                                    @{
                                        if((User.Identity.Name==el.IdentityUserName)||(User.IsInRole("Администратор")) ||( User.IsInRole("Модератор")))
                                        {
                                          <td class="col-md-1">
                                             <a class="btn btn-warning col-lg-12" asp-route-CommentID="@el.CommentID" asp-route-FurnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="DeleteComment">Удалить</a>
                                          </td>
                                        }
                                    }
                                </tr>
                            }
                        </table>
                    </div><br/>
                    if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-success" asp-route-FurnitureID="@furniture.FurnitureID" asp-controller="Furniture" asp-action="CreateComment">Добавить комментарий</a>
                    }
                    <br/><br/>
                }
            }
        </div>  
    </div>
    <div class="col-md-2">
        @{
            foreach (var el in Model.allFurniture)
            {
                <h3>@el.Name</h3>
                 if(el.Stock.StockName!="Нет")
                 {
                    <h3>Акция: @el.Stock.StockName</h3>
                    <h3><s>@el.Price ₽ </s>  @el.StockPrice ₽</h3>                            
                 }
                 else
                 {
                    <h3>@el.Price ₽</h3>
                 }
                 bool k = false;
                 foreach (var i in ViewBag.Items)
                 {
                    if (i == el.FurnitureID)
                    {
                        k = true;
                    }
                 }
                 if (k == true)
                 {
                     <button class="btn btn-light col-lg-12">В корзине</button>
                 }
                 else
                 {
                     <a class="btn btn-info col-lg-12" asp-route-Id="@el.FurnitureID" asp-controller="ShopCart" asp-action="addToCart">В корзину</a>
                 }
                 <a class="btn btn-info col-lg-12"  asp-controller="Home" asp-action="Index">Назад</a>
             }
          }
    </div>
</div>