Controllers/ColorController.cs
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class ColorController : Controller
    {
        private readonly IRepository<FurnitureColor> _allColor;

        public ColorController(IRepository<FurnitureColor> allColor)
        {
            _allColor = allColor;
        }
        public async Task<IActionResult> ColorList()
        {
            return View(await _allColor.ListAsync());
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public IActionResult CreateList()
        {
            return View();
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Create(string colorName, string color)
        {
            await _allColor.CreateAsync(new FurnitureColor { ColorName = colorName, Color=color});
            await _allColor.SaveAsync();
            return RedirectToAction("ColorList");
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Delete(int colorID)
        {
            await _allColor.DeleteAsync(colorID);
            await _allColor.SaveAsync();
            return RedirectToAction("ColorList");
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Edit(int colorID)
        {
            FurnitureColor FurnitureColor = await _allColor.GetAsync(colorID);

            return View(FurnitureColor);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Update(int colorID, string colorName,string color)
        {
            try
            {
                await _allColor.Update(new FurnitureColor { ColorID = colorID, ColorName = colorName, Color = color });
                await _allColor.SaveAsync();
                return RedirectToAction("ColorList");
            }
            catch
            {
                return RedirectToAction("ColorList");
            }
        }
    }
}

Controllers/KindController.cs
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class KindController : Controller
    {
        private readonly IRepository<FurnitureKind> _allKind;
        private readonly IWebHostEnvironment _environment;

        public KindController(IWebHostEnvironment environment,IRepository<FurnitureKind> allKind)
        {
            _allKind = allKind;
            _environment= environment;
        }
        public async Task<IActionResult> KindList()
        {
            return View(await _allKind.ListAsync());
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public IActionResult CreateList()
        {
            return View();
        }
        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Create(string kind,IFormFile pic)
        {
            FurnitureKind furnitureKind = new FurnitureKind();
            furnitureKind.Kind = kind;
            await _allKind.CreateAsync(furnitureKind);
            furnitureKind.Photo = await Photo(furnitureKind.KindID, pic);
            await _allKind.Update(furnitureKind);
            return RedirectToAction("KindList");
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Delete(int kindID)
        {   
            FileInfo fileInf = new FileInfo(_environment.WebRootPath + _allKind.GetAsync(kindID).Result.Photo);
            if (fileInf.Exists) fileInf.Delete();
            await _allKind.DeleteAsync(kindID);
            return RedirectToAction("KindList");
        }

        public async Task<string> Photo(int kindID, IFormFile pic)
        {
            if (pic != null)
            {
                await using (var memoryStream = new MemoryStream())
                {
                    await pic.CopyToAsync(memoryStream);
                    var img = Image.FromStream(memoryStream);
                    using (Bitmap newPic = new Bitmap(350, 300))
                    {
                        using (Graphics gr = Graphics.FromImage(newPic))
                        {
                            gr.DrawImage(img, 0, 0, 350, 300);
                            newPic.Save(_environment.WebRootPath + "/img/KindPhoto/" + kindID + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
                            memoryStream.Close();
                            newPic.Dispose();
                        }
                    }
                }                                                                                                                                                                                                                                                    
                return "/img/KindPhoto/" + kindID + ".jpg";
            }
            return string.Empty;
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Edit(int kindID)
        {
            FurnitureKind FurnitureKind = await _allKind.GetAsync(kindID);
            return View(FurnitureKind);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> Edit(FurnitureKind furnitureKind, IFormFile pic)
        {
            if(pic!=null)furnitureKind.Photo = await Photo(furnitureKind.KindID, pic);
            else if (System.IO.File.Exists(_environment.WebRootPath + "/img/KindPhoto/"+furnitureKind.KindID+ ".jpg"))
            {
                furnitureKind.Photo= "/img/KindPhoto/" + furnitureKind.KindID + ".jpg";
            }
            else furnitureKind.Photo = "/img/No Photo/no-photo.jpg";
            await _allKind.Update(furnitureKind);
            return RedirectToAction("KindList");
        }

    }
}

Controllers/OrderController.cs
using FurnitureStore.Data;
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.ViewModels;
using System.Xml.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using ClosedXML.Excel;
using OfficeOpenXml.Style;

namespace FurnitureStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationContext _applicationContext;
        private readonly IWebHostEnvironment _environment;
        private readonly IRepository<Order> _allOrders;
        private readonly ShopCart shopCart;
        public IEnumerable<Order> orders;

        public OrderController(IWebHostEnvironment environment, ApplicationContext applicationContext, IRepository<Order> allOrders,ShopCart shopCart)
        {
            this._applicationContext = applicationContext;
            this._allOrders = allOrders;
            this.shopCart = shopCart;
            _environment = environment;
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> OrderList()
        {
            OrderListViewModel ord = new OrderListViewModel
            {
                allOrders = await _allOrders.ListAsync()
            };
            return View(ord);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> OrderList(int numberFilter, DateTime dateFilter, DateTime dateFilter2, string fullNameFilter, string statusFilter)
        {
            OrderListViewModel ord = new OrderListViewModel();
            IEnumerable<Order> filter = await _allOrders.ListAsync();
            if (numberFilter!=0)
            {
                ord.allOrders= filter.Where(i=>i.OrderID==numberFilter);
            }
            else
            {
                filter = filter.Where(i => i.OrderTime >= dateFilter);
                if (dateFilter2 != new DateTime(0001, 01, 01, 0, 00, 00))
                {
                    filter = filter.Where(i => i.OrderTime <= dateFilter2);
                }
                if (fullNameFilter!="" && fullNameFilter != null)
                {
                    filter = filter.Where(i => (i.Surname.ToUpper()+" "+i.Name.ToUpper()+" "+i.MiddleName.ToUpper()).Contains(fullNameFilter.ToUpper()));
                }
                if (statusFilter == "Все" || statusFilter == null) { }
                else
                {
                    bool test = statusFilter == "Завершен" ? true : false;
                    filter = filter.Where(i => i.Status == test);
                }
                ord.allOrders= filter;
            }
            ViewBag.Orders = ord.allOrders;
            return View(ord);
        }

        public IActionResult ClientOrderList()
        {
            OrderListViewModel ord = new OrderListViewModel
            {
                allOrders =  _allOrders.ListAsync().Result.Where(c=>c.User==User.Identity.Name)
            };
            return View(ord);
        }

        public IActionResult OrderDetail(int id)
        {
            Order ord = _allOrders.GetAsync(id).Result;
            return View(ord);
        }
        public  IActionResult Create()
        {
            if (!shopCart.GetShopItems().Any())
            {
                return RedirectToAction("CartIsEmpty");
            }
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Authenticated");
            }
            ViewBag.User = _applicationContext.Users.Where(i => i.Email == User.Identity.Name).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Order order)
        {
            if (ModelState.IsValid)
            {
                order.User = User.Identity.Name;
                order.Status = false;
                await _allOrders.CreateAsync(order);
                return RedirectToAction("Complete") ;
            }
            
           return View(order);
        }

        public async Task<IActionResult> Delete (int OrderID)
        {
            await _allOrders.DeleteAsync(OrderID);
            return RedirectToAction("OrderList");
        }
        public IActionResult Confirmation(int id)
        {
            _allOrders.GetAsync(id).Result.Status = true;
            _allOrders.SaveAsync();
            return RedirectToAction("ClientOrderList");
        }
        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан ";
            return View();
        }
        public IActionResult CartIsEmpty()
        {
            ViewBag.Message = "Корзина пуста";
            return View();
        }

        public IActionResult Authenticated()
        {
            ViewBag.Message = "Необходимо авторизоваться";
            return View();
        }

        public async Task<IActionResult> Export(string test)
        {
            IEnumerable<Order> allorders= await _allOrders.ListAsync();
            List<Order> ordersList=new List<Order>();
            string[] orders= test.Split('_', StringSplitOptions.RemoveEmptyEntries);
            foreach (var el in orders)
            {
                foreach (var order in allorders)
                {
                    if (order.OrderID == Convert.ToInt32(el))
                    {
                        ordersList.Add(order);
                    }
                }
            }
            int i = 1;
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var worksheet = workbook.Worksheets.Add("Отчет");
                worksheet.Cell("A1").Value = "Номер Заказа";
                worksheet.Cell("B1").Value = "Фамилия";
                worksheet.Cell("C1").Value = "Имя";
                worksheet.Cell("D1").Value = "Отчество";
                worksheet.Cell("E1").Value = "Дата и время";
                worksheet.Cell("F1").Value = "Статус";
                worksheet.Cell("G1").Value = "Сумма";
                worksheet.Cell("I1").Value = "Общая сумма заказов";
                worksheet.Cell("J1").Value = "Всего заказов";
                worksheet.Column(1).Width = 18;
                worksheet.Column(2).Width = 18;
                worksheet.Column(3).Width = 18;
                worksheet.Column(4).Width = 18;
                worksheet.Column(5).Width = 18;
                worksheet.Column(6).Width = 18;
                worksheet.Column(7).Width = 18;
                worksheet.Column(9).Width = 23;
                worksheet.Column(10).Width = 23;
                worksheet.Row(1).Style.Font.Bold = true;
                int sum = 0;
                foreach (var order in ordersList)
                {
                    worksheet.Cell(i + 1, 1).Value = order.OrderID;
                    worksheet.Cell(i + 1, 2).Value = order.Surname;
                    worksheet.Cell(i + 1, 3).Value = order.Name;
                    worksheet.Cell(i + 1, 4).Value = order.MiddleName;
                    worksheet.Cell(i + 1, 5).Value = order.OrderTime;
                    string status = "";
                    if (order.Status == false) status = "Доставка";
                    else status = "Завершен";
                    worksheet.Cell(i + 1, 6).Value = status;
                    int price = 0;
                    foreach (var detail in order.OrderDetail)
                    {
                        price += detail.Price;
                    }
                    worksheet.Cell(i + 1, 7).Value = price;
                    i++;
                    sum += price;
                }
                worksheet.Cell(2, 9).Value = sum;
                worksheet.Cell(2, 10).Value = ordersList.Count();
                worksheet.Cells().Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    stream.Flush();

                    return new FileContentResult(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        FileDownloadName = $"Отчет_{DateTime.UtcNow.ToShortDateString()}.xlsx"
                    };
                }
            }
        }
    }
}

Controllers/TypeController.cs
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class TypeController : Controller
    {
        private readonly IRepository<FurnitureType> _allType;

        public TypeController(IRepository<FurnitureType> allType)
        {
            _allType = allType;
        }
        public async Task<IActionResult> TypeList()
        {
            return View(await _allType.ListAsync());
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public IActionResult CreateList()
        {
            return View();
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Create(string type)
        {
            await _allType.CreateAsync(new FurnitureType { Type = type });
            await _allType.SaveAsync();
            return RedirectToAction("TypeList");
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Delete(int typeID)
        {
            await _allType.DeleteAsync(typeID);
            await _allType.SaveAsync();
            return RedirectToAction("TypeList");
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Edit(int typeID)
        {
            FurnitureType FurnitureType = await _allType.GetAsync(typeID);

            return View(FurnitureType);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Update(int typeID, string type)
        {
            try
            {
                await _allType.Update(new FurnitureType { TypeID = typeID, Type = type });
                await _allType.SaveAsync();
                return RedirectToAction("TypeList");
            }
            catch
            {
                return RedirectToAction("TypeList");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>FurnitureStore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="https://fonts.gstatic.com/" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CNunito:300,300i,400,400i,600,600i,700,700i%7CPoppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<style>
    body{
        font-family:'Open Sans',sans-serif;
    }
</style>
<body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Навигация</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="HomePage" asp-action="Index">FurnitureStore</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>&nbsp&nbsp&nbsp</li>
                    <li>
                        <a class="nav-link text-dark" asp-controller="Furniture" asp-action="List">Мебель</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-controller="Stock" asp-action="List">Акции</a>
                    </li>
                    <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShopCart" asp-action="Index">Корзина</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-route-UserName="@User.Identity.Name" asp-controller="Users" asp-action="Profile">Профиль</a>
                        </li>
                         <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ClientOrderList">Заказы</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Администратор") || User.IsInRole("Модератор")))
                        {
                             <li>
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="OrderList">Все заказы</a>
                             </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown">Редактор<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    @if (User.Identity.IsAuthenticated && (User.IsInRole("Администратор"))){
                                    <li><a asp-controller="Users" asp-action="">Список пользователей</a></li>
                                    <li><a asp-controller="Roles" asp-action="Index">Управление ролями</a></li>
                                    <li class="divider"></li>
                                    }
                                    <li><a asp-controller="Kind" asp-action="KindList">Виды</a></li>
                                    <li><a asp-controller="Type" asp-action="TypeList">Типы</a></li>
                                    <li><a asp-controller="Color" asp-action="ColorList">Цвета</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-controller="Furniture" asp-action="FurnitureList">Мебель</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-controller="Stock" asp-action="Index">Акции</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-controller="HomePage" asp-action="List">Главная страница</a></li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="search" name="search" class="form-control" placeholder="Поиск">
                    </div>
                    <button asp-controller="Furniture" asp-action="Search" class="btn btn-default">Отправить</button>
                </form>
                <ul class="nav navbar-nav d-flex flex-row bd-highlight">
                    @if (User.Identity.IsAuthenticated == false)
                    {
                        <li>
                            <a class="nav-link p-2 bd-highlight text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                        <li>
                            <a class="nav-link p-2 bd-highlight text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        </li>  
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Exit">Выход</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>