Controllers/HomePageController.cs
using System.IO;
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.Models;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace FurnitureStore.Controllers
{
    public class HomePageController : Controller
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IRepository<Furniture> _allFurnituries;
        private readonly IRepository<HomePage> _allHomePages;
        private readonly IRepository<FurnitureKind> _furnitureKind;
        private readonly IRepository<FurnitureType> _furnitureType;
        private readonly IRepository<FurnitureColor> _furnitureColor;
        private readonly ShopCart _shopCart;
        private readonly IRepository<Stock> _Stock;

        public HomePageController(IWebHostEnvironment environment, IRepository<HomePage> allHomePages, ShopCart shopCart, IRepository<Furniture> iallFurnituries,
            IRepository<FurnitureKind> ifurnitureKind, IRepository<FurnitureType> ifurnitureType, IRepository<FurnitureColor> ifurnitureColor, IRepository<Stock> _iStock)
        {
            _allFurnituries = iallFurnituries;
            _furnitureKind = ifurnitureKind;
            _furnitureType = ifurnitureType;
            _furnitureColor = ifurnitureColor;
            _shopCart = shopCart;
            _Stock = _iStock;
            _allHomePages = allHomePages;
            _environment = environment;
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Create(string error)
        {
            ViewBag.Stock = await _Stock.ListAsync();
            ViewData["Error"] = error;
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            
            return View();
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> Create(HomePage homePage,IFormFile t1, IFormFile t2, IFormFile t3,IFormFile c1,IFormFile c2,IFormFile c3, int stock1, int stock2, int stock3)
        {

            ViewBag.Stock = await _Stock.ListAsync();
            List<HomePage> pages = (List<HomePage>)await _allHomePages.ListAsync();
            if (pages.Exists(i => i.Name.ToLower() == homePage.Name.ToLower()))
            {
                return RedirectToAction("Create", new { error = "Страница с таким названием уже существует" });
            }
            else
            {
                await _allHomePages.CreateAsync(homePage);
                await _allHomePages.SaveAsync();
                homePage.Stock_1 = await _Stock.GetAsync(stock1);
                homePage.Stock_2 = await _Stock.GetAsync(stock2);
                homePage.Stock_3 = await _Stock.GetAsync(stock3);
                homePage.TitleImage_1 = await PhotoTitle(homePage.HomePageID + "_1", t1);
                homePage.TitleImage_2 = await PhotoTitle(homePage.HomePageID + "_2", t2);
                homePage.TitleImage_3 = await PhotoTitle(homePage.HomePageID + "_3", t3);
                homePage.CircleImage_1 = await PhotoCircle(homePage.HomePageID + "_1", c1);
                homePage.CircleImage_2 = await PhotoCircle(homePage.HomePageID + "_2", c2);
                homePage.CircleImage_3 = await PhotoCircle(homePage.HomePageID + "_3", c3);
                await _allHomePages.Update(homePage);
                await _allHomePages.SaveAsync();
                return RedirectToAction("List");
            }
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Stock = await _Stock.ListAsync();
            HomePage page = await _allHomePages.GetAsync(id);
            return View(page);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<IActionResult> Edit(HomePage page, IFormFile imgT1, IFormFile imgT2, IFormFile imgT3, IFormFile imgC1, IFormFile imgC2, IFormFile imgC3, int stock1, int stock2, int stock3)
        {
            if (ModelState.IsValid)
            {
                Console.WriteLine(page.Stock_1);
                ViewBag.Stock = await _Stock.ListAsync();
                page.Stock_1 = await _Stock.GetAsync(stock1);
                page.Stock_2 = await _Stock.GetAsync(stock2);
                page.Stock_3 = await _Stock.GetAsync(stock3);
                page.TitleImage_1 = await Check(imgT1, page.HomePageID, 1, "/img/TitleImage/", 1);
                page.TitleImage_2 = await Check(imgT2, page.HomePageID, 2, "/img/TitleImage/", 1);
                page.TitleImage_3 = await Check(imgT3, page.HomePageID, 3, "/img/TitleImage/", 1);
                page.CircleImage_1 = await Check(imgC1, page.HomePageID, 1, "/img/CircleImage/", 0);
                page.CircleImage_2 = await Check(imgC2, page.HomePageID, 2, "/img/CircleImage/", 0);
                page.CircleImage_3 = await Check(imgC3, page.HomePageID, 3, "/img/CircleImage/", 0);
                await _allHomePages.Update(page);
                return RedirectToAction("List");
            }
            return View(page);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Delete(int id)
        {
            FileInfo fileInf = new FileInfo(_environment.WebRootPath+_allHomePages.GetAsync(id).Result.CircleImage_1);
            if (fileInf.Exists) fileInf.Delete();
            fileInf = new FileInfo(_environment.WebRootPath + _allHomePages.GetAsync(id).Result.CircleImage_2);
            if (fileInf.Exists) fileInf.Delete();
            fileInf = new FileInfo(_environment.WebRootPath + _allHomePages.GetAsync(id).Result.CircleImage_3);
            if (fileInf.Exists) fileInf.Delete();
            fileInf = new FileInfo(_environment.WebRootPath + _allHomePages.GetAsync(id).Result.TitleImage_1);
            if (fileInf.Exists) fileInf.Delete();
            fileInf = new FileInfo(_environment.WebRootPath + _allHomePages.GetAsync(id).Result.TitleImage_2);
            if (fileInf.Exists) fileInf.Delete();
            fileInf = new FileInfo(_environment.WebRootPath + _allHomePages.GetAsync(id).Result.TitleImage_3);
            if (fileInf.Exists) fileInf.Delete();
            await _allHomePages.DeleteAsync(id);
            await _allHomePages.SaveAsync();
            return RedirectToAction("List");
        }


        public async Task<string> Check(IFormFile file, int id, int i,string path,int k)
        {
            if (file != null)
            {
                if(k==1)return await PhotoTitle(id + "_" + i, file);
                else return await PhotoCircle(id + "_" + i, file);
            }
            else if (System.IO.File.Exists(_environment.WebRootPath + path + id + "_" + i + ".jpg"))
            {
                return path + id + "_" + i + ".jpg";
            }
            else return "/img/No Photo/no-photo.jpg";
        }
        public async Task<string> PhotoTitle(string id, IFormFile pic)
        {
            if (pic != null)
            {
                await using (var memoryStream = new MemoryStream())
                {
                    await pic.CopyToAsync(memoryStream);
                    var img = Image.FromStream(memoryStream);
                    using (Bitmap newPic = new Bitmap(1920, 600))
                    {
                        using (Graphics gr = Graphics.FromImage(newPic))
                        {
                            gr.DrawImage(img, 0, 0, 1920, 600);
                            newPic.Save(_environment.WebRootPath + "/img/TitleImage/" + id + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
                            memoryStream.Close();
                            newPic.Dispose();
                        }
                    }
                }
                return "/img/TitleImage/" + id + ".jpg";
            }
            else return "/img/No Photo/no-photo.jpg";
        }
        public async Task<string> PhotoCircle(string id, IFormFile pic)
        {
            if (pic != null)
            {
                await using (var memoryStream = new MemoryStream())
                {
                    await pic.CopyToAsync(memoryStream);
                    var img = Image.FromStream(memoryStream);
                    using (Bitmap newPic = new Bitmap(350, 300))
                    {
                        using (Graphics gr = Graphics.FromImage(newPic))
                        {
                            gr.DrawImage(img, 0, 0, 350, 300);
                            newPic.Save(_environment.WebRootPath + "/img/CircleImage/" + id + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
                            memoryStream.Close();
                            newPic.Dispose();
                        }
                    }
                }
                return "/img/CircleImage/" + id + ".jpg";
            }
            else return "/img/No Photo/no-photo.jpg";
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Items = _shopCart.GetShopItems().Select(i => i.furniture.FurnitureID);
            ViewBag.Kinds = await _furnitureKind.ListAsync();
            ViewBag.Types = await _furnitureType.ListAsync();
            ViewBag.Colors = await _furnitureColor.ListAsync();
            ViewBag.Furniture =  _allFurnituries.ListAsync().Result.Where(i=>i.isFavorite);
            ViewData["Path"] = _environment.WebRootPath;
            HomePage homePage;
            IEnumerable<HomePage> homePages = _allHomePages.ListAsync().Result.Where(i => i.isFavorite);
            if (homePages.Count() == 0)
            {

Controllers/ShopCartController.cs
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.Data.Repository;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IRepository<Furniture> _furRep;
        private readonly ShopCart _shopCart;
        private readonly IWebHostEnvironment _environment;

        public ShopCartController(IWebHostEnvironment environment,IRepository<Furniture> furRep,ShopCart shopCart)
        {
            _environment = environment;
            _furRep = furRep;
            _shopCart = shopCart;
        }
        public ViewResult Index()
        {
            ViewData["Path"] = _environment.WebRootPath;
            _shopCart.ListShopItems = _shopCart.GetShopItems();
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _furRep.GetAsync(id).Result;
            if (item != null) 
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult Delete(int id)
        {
            _shopCart.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/StockController.cs
using FurnitureStore.Data;
using FurnitureStore.Data.Interfaces;
using FurnitureStore.Data.Models;
using FurnitureStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

namespace FurnitureStore.Controllers
{
    public class StockController : Controller
    {
        private readonly IRepository<Stock> _allStock;
        private readonly IWebHostEnvironment _environment;

        public async Task<IActionResult> Index()
        {
            StockListViewModel stockView = new StockListViewModel() { allStock = await _allStock.ListAsync() };
            return View(stockView);
        }

        public StockController(IRepository<Stock> allStock, IWebHostEnvironment IWebHostEnvironment)
        {
            _allStock = allStock;
            _environment = IWebHostEnvironment;
        }
        public async Task<IActionResult> StockPage(int StockID)
        {
            return View(await _allStock.GetAsync(StockID));
        }

        public async Task<IActionResult> StockList()
        {
            return View(await _allStock.ListAsync());
        }

        [Authorize(Roles = "Администратор, Модератор")]
        public ActionResult Create(string error)
        {
            ViewData["Error"] = error;
            return View();
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<ActionResult> Create(Stock stock,IFormFile pic)
        {
            List<Stock> stocks = (List<Stock>)await _allStock.ListAsync();
            if(stocks.Exists(i=>i.StockName.ToLower() == stock.StockName.ToLower()))
            {
                return RedirectToAction("Create",new {error="Акция с таким названием уже существует" });
            }
            await _allStock.CreateAsync(stock);
            await _allStock.SaveAsync();
            stock.Photo= await Photo(stock.StockID.ToString(), pic);
            await _allStock.Update(stock);
            await _allStock.SaveAsync();
            return RedirectToAction("Index");
        }

        public async Task<string> Photo(string stockID, IFormFile pic)
        {
            if (pic != null)
            {
                await using (var memoryStream = new MemoryStream())
                {
                    await pic.CopyToAsync(memoryStream);
                    var img = Image.FromStream(memoryStream);
                    using (Bitmap newPic = new Bitmap(350, 300))
                    {
                        using (Graphics gr = Graphics.FromImage(newPic))
                        {
                            gr.DrawImage(img, 0, 0, 350, 300);
                            newPic.Save(_environment.WebRootPath + "/img/Stock/" + stockID + ".jpg", System.Drawing.Imaging.ImageFormat.Jpeg);
                            memoryStream.Close();
                            newPic.Dispose();
                        }
                    }
                }
                return "/img/Stock/" + stockID + ".jpg";
            }
            else return "";
        }


        [Authorize(Roles = "Администратор, Модератор")]
        [HttpGet]
        public async Task<ActionResult> Edit(int id,string error)
        {
            Stock stock = await _allStock.GetAsync(id);
            ViewData["Error"] = error;
            return View(stock);
        }

        [Authorize(Roles = "Администратор, Модератор")]
        [HttpPost]
        public async Task<ActionResult> Edit(Stock stock, IFormFile pic)
        {
            if (pic != null) stock.Photo = await Photo(stock.StockID.ToString(), pic);
            else stock.Photo = "/img/Stock/" + stock.StockID + ".jpg";
            await _allStock.Update(stock);
            await _allStock.SaveAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> List()
        {
            StockListViewModel stockView = new StockListViewModel() { allStock = await _allStock.ListAsync() };
            return View(stockView);
        }
        [Authorize(Roles = "Администратор, Модератор")]
        public async Task<IActionResult> Delete(int id)
        {
            await _allStock.DeleteAsync(id);
            await _allStock.SaveAsync();
            return RedirectToAction("Index");
        }
    }
}

Views/HomePage/Index.cshtml
@using FurnitureStore.Data.Models
@model HomePage
<style>
    .container {
            width: 100%;
        }
    .border {
            border-width:2px;
            border-color:white;
        }
    .alert-secondary {
    color: #383d41;
    background-color: #f1f1f1;
    border-color: #d6d8db;
    }
    .btn-secondary {
    color: #fff;
    background-color: #6c757d;
    border-color: #6c757d;
    }
</style>

<form method="post" asp-controller="Furniture" asp-action="List" enctype="multipart/form-data">
@if (Model.ImageBlock)
{
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
    <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="@Model.TitleImage_1" alt="New York">
                <div class="carousel-caption">
                    <p>@Model.Title_1</p>
                </div>      
            </div>

            <div class="item">
                <img src="@Model.TitleImage_2" alt="Chicago">
                <div class="carousel-caption">
                    <p>@Model.Title_2</p>
                </div>      
            </div>

            <div class="item">
                <img src="@Model.TitleImage_3" alt="Los Angeles">
                <div class="carousel-caption">
                    <p>@Model.Title_3</p>
                </div>      
            </div>
        </div>
    </div>
}

@if (Model.CharacteristicsBlock)
{
    <div id="band" class="container text-center">
        <br>
        <div class="row">
            <div class="col-sm-4">
                <a href="#demo" data-toggle="collapse">
                    <img src="@Model.CircleImage_1" class="img-circle person" width="255" height="255">
                </a>
                <div id="demo" class="collapse" >
                    <p style="text-align:center">@Model.CircleText_1</p>
                </div>
            </div>
            <div class="col-sm-4">
                <a href="#demo2" data-toggle="collapse">
                    <img src="@Model.CircleImage_2" class="img-circle person" width="255" height="255">
                </a>
                <div id="demo2" class="collapse">
                    <p>@Model.CircleText_2</p>
                </div>
            </div>
            <div class="col-sm-4">
                <a href="#demo3" data-toggle="collapse">
                    <img src="@Model.CircleImage_3" class="img-circle person" width="255" height="255">
                </a>
                <div id="demo3" class="collapse">
                    <p>@Model.CircleText_3</p>
                </div>
            </div>
        </div>
    </div>
}

@if (Model.StockBlock)
{
    <br><br>
    <div id="tour" class="bg-1">
        <div class="container">
            <h2 class="text-center"><strong>Акции</strong></h2>
            <br><br>
            <div class="row text-center">
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @{
                            if (Model.Stock_1 != null && System.IO.File.Exists(ViewData["Path"] + Model.Stock_1.Photo))
                            {
                                <img src="@Model.Stock_1.Photo" alt="Paris" width="400" height="300">
                            }
                            else
                            {
                                <img src="/img/No Photo/no-photo.jpg" alt="Paris" width="400" height="300">
                            }
                        }
                        <p><strong>@Model.Stock_1.StockName</strong></p>
                        <p>Friday 27 November 2015</p>
                        <button class="btn" asp-controller="Stock" asp-action="StockPage" asp-route-StockID="@Model.Stock_1.StockID">Подробнее</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @{
                            if (Model.Stock_2 != null && System.IO.File.Exists(ViewData["Path"] + Model.Stock_2.Photo))
                            {
                                <img src="@Model.Stock_2.Photo" width="400" height="300">
                            }
                            else
                            {
                                <img src="/img/No Photo/no-photo.jpg" width="400" height="300">
                            }
                        }
                        <p><strong>@Model.Stock_2.StockName</strong></p>
                        <p>Saturday 28 November 2015</p>
                        <button class="btn" asp-controller="Stock" asp-action="StockPage" asp-route-StockID="@Model.Stock_2.StockID">Подробнее</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @{
                            if (Model.Stock_3 != null && System.IO.File.Exists(ViewData["Path"] + Model.Stock_3.Photo))
                            {
                                <img src="@Model.Stock_3.Photo" width="400" height="300">
                            }
                            else
                            {
                                <img src="/img/No Photo/no-photo.jpg" width="400" height="300">
                            }
                        }
                        <p><strong>@Model.Stock_3.StockName</strong></p>
                        <p>Sunday 29 November 2015</p>
                        <button class="btn" asp-controller="Stock" asp-action="StockPage" asp-route-StockID="@Model.Stock_3.StockID">Подробнее</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@{
    if(Model.KindBlock)
    {
        <br><br>
        <div class="row">
            <div class="text-center">
                <h2 class="text-center"><strong>Категории</strong></h2>
                <br><br>
                @foreach(var el in ViewBag.Kinds)
                {       
                    <div class="col-md-2">
                        <button type="submit" method="Post" asp-controller="Furniture" asp-action="List" asp-route-kindFilter="@el.Kind">
                            <figure>
                                <p><img class="img-circle person" width="200" height="200" src="@el.Photo" /></p>
                                @el.Kind
                            </figure>
                        </button>
                    </div>
                }
            </div>
        </div>
    }
}

@{
    if(Model.OurChoiceBlock)
    {
        <br><br>
        <h2 class="text-center"><strong>Наш выбор</strong></h2>
        <br><br>
        int carousel = 1;
        foreach (var el in ViewBag.Furniture)
        {
            <div class="alert alert-secondary col-md-2 border">
                <div class="row">
                    <div id="@carousel" class="carousel slide" data-ride="carousel" style="max-height:20em">
                        <ol class="carousel-indicators">
                        @{
                            int p = 0;
                            if(System.IO.File.Exists(ViewData["Path"] + el.Photo1))
                            {
                                <li data-target="@carousel" data-slide-to="0" class="active"></li>
                                p++;
                            }
                            if(System.IO.File.Exists(ViewData["Path"] + el.Photo2))
                            {
                                <li data-target="@carousel" data-slide-to="1"></li>
                                p++;
                            }
                            if(System.IO.File.Exists(ViewData["Path"] + el.Photo3))
                            {
                                <li data-target="@carousel" data-slide-to="2"></li>
                                p++;
                            }
                            if(p==0)
                            {
                                <li data-target="@carousel" data-slide-to="1" class="active"></li>
                            }
                        }
                        </ol>
                        <div class="carousel-inner" style="max-height:20em">
                        @{
                            if (p == 0)
                            {
                                <div class="item active">
                                    <img src="~/img/No Photo/no-photo.jpg" class="center-block"  style="max-height:20em">
                                </div>
                            }
                            else
                            {
                                if (System.IO.File.Exists(ViewData["Path"] + el.Photo1))
                                {
                                    <div class="item active">
                                        <img src="@el.Photo1" class="center-block"  style="max-height:20em">
                                    </div>
                                }
                                if (System.IO.File.Exists(ViewData["Path"] + el.Photo2))
                                {
                                    <div class="item">
                                        <img src="@el.Photo2" class="center-block"  style="max-height:20em">
                                    </div>
                                }
                                if (System.IO.File.Exists(ViewData["Path"] + el.Photo3))
                                {
                                    <div class="item">
                                        <img src="@el.Photo3" class="center-block"  style="max-height:20em">
                                    </div>
                                }
                            }
                         }
                         </div>
                        <a class="left carousel-control" href="#@carousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#@carousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <br/>
                        <label style="text-overflow:ellipsis; overflow: hidden; white-space: nowrap;">@el.Name</label>
                        <br/>
                        @{                                       
                            if(el.Stock.StockName!="Нет")
                            {
                                <h4>@el.StockPrice ₽ &nbsp <a style="color:White; text-shadow: red 0 0 4px;" asp-controller="Stock" asp-action="StockPage" asp-route-StockID="@el.StockID"><strong>Акция</strong></a> </h4> 
                            }
                            else
                            {
                                <h4>@el.Price ₽</h4>
                            }
                         }
                         @if(el.FurnitureKind.Kind=="Кухонная мебель"||el.FurnitureKind.Kind=="Офисная мебель"||el.FurnitureKind.Kind=="Дизайнерская мебель")
                         {
                             <h5>Вид: @el.FurnitureKind.Kind &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</h5>
                         }
                         else
                         {
                             <h5>Вид: @el.FurnitureKind.Kind</h5>
                         }
                         <h5>Тип: @el.FurnitureType.Type</h5>
                         <h5>Цвет: @el.FurnitureColor.ColorName</h5>
                         <h5 style="text-overflow:ellipsis; overflow: hidden; white-space: nowrap;">Материал: @el.Material</h5>
                         <h5>В наличии: @el.Number</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <a class="btn btn-info col-lg-12" asp-route-furnitureID="@el.FurnitureID" asp-controller="Furniture" asp-action="FurniturePage">Выбрать</a>
                        @{
                            bool k = false;
                            foreach (var i in ViewBag.Items)
                            {
                                if (i == el.FurnitureID)
                                {
                                    k = true;
                                }
                            }
                            if (k == true)
                            {
                                <button class="btn btn-secondary col-lg-12">В корзине</button>
                            }
                            else
                            {
                                <a class="btn btn-info col-lg-12" asp-route-Id="@el.FurnitureID" asp-controller="ShopCart" asp-action="addToCart">В корзину</a>
                            }
                         }
                    </div>
                </div>
            </div>
            carousel++;
        }
    }                              
}
</form>

Views/HomePage/List.cshtml
@using FurnitureStore.ViewModels
@model HomePageListViewModel

<style>
        .container {
            width: 85%;
            padding-right: 10px;
            padding-left: 10px;
        }
        .border {
            border-width:2px;
            border-color:white;
        }
</style>
<form asp-controller="HomePage" asp-action="FavoritePage">
    <div class="row">
        <div class="col-md-2">
            <table class="col-md-11 ">
                <tr>
                    <td>
                        <label>Главная страница</label>
                   </td>
                </tr>
                <tr>
                    <td>
                        <h5><select class="col-md-12" asp-items="@ViewBag.HomePages" name="id"></select></h5>
                   </td>
                </tr>
                <tr>
                    <td>
                        <br/>
                        <button type="submit" class="btn btn-info" asp-controller="HomePage" asp-action="FavoritePage">Сохранить</button>
                   </td> 
                </tr>
            </table>  
        </div>
        <div class="col-md-8">
        @{
            foreach (var el in Model.allHomePages)
            {
                <din class="alert alert-info col-md-3 border">
                    <h4>@el.Name</h4>
                    @if(el.HomePageID!=1)
                    {
                        <a class="btn btn-info" asp-controller="HomePage" asp-route-error="" asp-action="Edit" asp-route-id="@el.HomePageID">Изменить</a>
                        <a class="btn btn-danger" asp-controller="HomePage" asp-action="Delete" asp-route-id="@el.HomePageID">Удалить</a>
                    }
                    
                    <br/>
                </din>  
            }
        }
        </div>
        <div class="col-md-2">
            <a class="btn btn-primary col-md-12" asp-controller="HomePage" asp-route-error="" asp-action="Create" >Добавить</a>
        </div>
    </div>
</form>